// Pre-generated template data for server-side use (avoids ES module import issues)
export const templateData = [
  // Minimalist Category (25 templates)
  { name: 'Minimalist Blue', category: 'minimalist', description: 'Clean, ATS-friendly design with blue accents', isPremium: false },
  { name: 'Minimalist Gray', category: 'minimalist', description: 'Professional gray minimalist layout', isPremium: false },
  { name: 'Minimalist White', category: 'minimalist', description: 'Pure white background with minimal elements', isPremium: false },
  { name: 'Minimalist Teal', category: 'minimalist', description: 'Modern teal accents on clean background', isPremium: true },
  { name: 'Minimalist Green', category: 'minimalist', description: 'Fresh green minimal design', isPremium: false },
  { name: 'Minimalist Black', category: 'minimalist', description: 'Elegant black and white contrast', isPremium: true },
  { name: 'Minimalist Purple', category: 'minimalist', description: 'Subtle purple minimal layout', isPremium: true },
  { name: 'Minimalist Navy', category: 'minimalist', description: 'Professional navy blue minimal design', isPremium: false },
  { name: 'Minimalist Light', category: 'minimalist', description: 'Ultra-light minimal template', isPremium: false },
  { name: 'Minimalist Modern', category: 'minimalist', description: 'Modern minimal with geometric elements', isPremium: true },
  { name: 'Minimalist Corporate', category: 'minimalist', description: 'Corporate-focused minimal design', isPremium: false },
  { name: 'Minimalist Tech', category: 'minimalist', description: 'Tech industry minimal template', isPremium: true },
  { name: 'Minimalist Healthcare', category: 'minimalist', description: 'Healthcare professional minimal design', isPremium: false },
  { name: 'Minimalist Finance', category: 'minimalist', description: 'Financial sector minimal template', isPremium: true },
  { name: 'Minimalist Education', category: 'minimalist', description: 'Academic minimal layout', isPremium: false },
  { name: 'Minimalist Creative', category: 'minimalist', description: 'Creative industry minimal design', isPremium: true },
  { name: 'Minimalist Executive', category: 'minimalist', description: 'Executive-level minimal template', isPremium: true },
  { name: 'Minimalist Entry Level', category: 'minimalist', description: 'Entry-level professional minimal', isPremium: false },
  { name: 'Minimalist Senior', category: 'minimalist', description: 'Senior professional minimal design', isPremium: true },
  { name: 'Minimalist Consultant', category: 'minimalist', description: 'Consulting industry minimal template', isPremium: true },
  { name: 'Minimalist Startup', category: 'minimalist', description: 'Startup-focused minimal design', isPremium: false },
  { name: 'Minimalist Remote', category: 'minimalist', description: 'Remote work minimal template', isPremium: false },
  { name: 'Minimalist International', category: 'minimalist', description: 'International minimal design', isPremium: true },
  { name: 'Minimalist Bilingual', category: 'minimalist', description: 'Bilingual minimal template', isPremium: true },
  { name: 'Minimalist ATS Pro', category: 'minimalist', description: 'Maximum ATS optimization minimal', isPremium: true },

  // Creative Category (25 templates)
  { name: 'Creative Burst', category: 'creative', description: 'Vibrant creative design with color gradients', isPremium: true },
  { name: 'Creative Modern', category: 'creative', description: 'Modern creative layout with infographic elements', isPremium: false },
  { name: 'Creative Bold', category: 'creative', description: 'Bold creative design for standout applications', isPremium: true },
  { name: 'Creative Designer', category: 'creative', description: 'Specialized for graphic designers', isPremium: true },
  { name: 'Creative UX', category: 'creative', description: 'UX/UI designer focused creative template', isPremium: true },
  { name: 'Creative Marketing', category: 'creative', description: 'Marketing professional creative design', isPremium: false },
  { name: 'Creative Portfolio', category: 'creative', description: 'Portfolio showcase creative template', isPremium: true },
  { name: 'Creative Infographic', category: 'creative', description: 'Infographic-style creative resume', isPremium: true },
  { name: 'Creative Colorful', category: 'creative', description: 'Colorful creative layout', isPremium: false },
  { name: 'Creative Artistic', category: 'creative', description: 'Artistic creative design', isPremium: true },
  { name: 'Creative Media', category: 'creative', description: 'Media industry creative template', isPremium: true },
  { name: 'Creative Digital', category: 'creative', description: 'Digital creative professional design', isPremium: false },
  { name: 'Creative Agency', category: 'creative', description: 'Creative agency professional template', isPremium: true },
  { name: 'Creative Freelancer', category: 'creative', description: 'Freelancer creative design', isPremium: false },
  { name: 'Creative Startup', category: 'creative', description: 'Startup creative professional template', isPremium: true },
  { name: 'Creative Social Media', category: 'creative', description: 'Social media manager creative design', isPremium: false },
  { name: 'Creative Content', category: 'creative', description: 'Content creator creative template', isPremium: true },
  { name: 'Creative Brand', category: 'creative', description: 'Brand manager creative design', isPremium: true },
  { name: 'Creative Video', category: 'creative', description: 'Video production creative template', isPremium: true },
  { name: 'Creative Photography', category: 'creative', description: 'Photography creative design', isPremium: false },
  { name: 'Creative Fashion', category: 'creative', description: 'Fashion industry creative template', isPremium: true },
  { name: 'Creative Entertainment', category: 'creative', description: 'Entertainment industry creative design', isPremium: true },
  { name: 'Creative Gaming', category: 'creative', description: 'Gaming industry creative template', isPremium: true },
  { name: 'Creative Architecture', category: 'creative', description: 'Architecture creative design', isPremium: true },
  { name: 'Creative Innovation', category: 'creative', description: 'Innovation-focused creative template', isPremium: true },

  // Modern Category (25 templates)
  { name: 'Modern Professional', category: 'modern', description: 'Contemporary professional design', isPremium: false },
  { name: 'Modern Blue', category: 'modern', description: 'Modern blue professional template', isPremium: false },
  { name: 'Modern Tech', category: 'modern', description: 'Technology industry modern design', isPremium: true },
  { name: 'Modern Corporate', category: 'modern', description: 'Corporate modern professional template', isPremium: false },
  { name: 'Modern Startup', category: 'modern', description: 'Startup-focused modern design', isPremium: true },
  { name: 'Modern Clean', category: 'modern', description: 'Clean modern professional layout', isPremium: false },
  { name: 'Modern Elegant', category: 'modern', description: 'Elegant modern design', isPremium: true },
  { name: 'Modern Business', category: 'modern', description: 'Business professional modern template', isPremium: false },
  { name: 'Modern Executive', category: 'modern', description: 'Executive modern design', isPremium: true },
  { name: 'Modern Manager', category: 'modern', description: 'Management-focused modern template', isPremium: true },
  { name: 'Modern Analyst', category: 'modern', description: 'Analyst modern professional design', isPremium: false },
  { name: 'Modern Consultant', category: 'modern', description: 'Consulting modern template', isPremium: true },
  { name: 'Modern Sales', category: 'modern', description: 'Sales professional modern design', isPremium: false },
  { name: 'Modern Marketing', category: 'modern', description: 'Marketing modern template', isPremium: false },
  { name: 'Modern Finance', category: 'modern', description: 'Finance industry modern design', isPremium: true },
  { name: 'Modern Healthcare', category: 'modern', description: 'Healthcare modern professional template', isPremium: false },
  { name: 'Modern Education', category: 'modern', description: 'Education modern design', isPremium: false },
  { name: 'Modern Engineering', category: 'modern', description: 'Engineering modern template', isPremium: true },
  { name: 'Modern Product', category: 'modern', description: 'Product management modern design', isPremium: true },
  { name: 'Modern Operations', category: 'modern', description: 'Operations modern template', isPremium: false },
  { name: 'Modern Strategy', category: 'modern', description: 'Strategy modern professional design', isPremium: true },
  { name: 'Modern Innovation', category: 'modern', description: 'Innovation-focused modern template', isPremium: true },
  { name: 'Modern Global', category: 'modern', description: 'Global modern design', isPremium: true },
  { name: 'Modern Remote', category: 'modern', description: 'Remote work modern template', isPremium: false },
  { name: 'Modern Hybrid', category: 'modern', description: 'Hybrid work modern design', isPremium: false },

  // Executive Category (25 templates)
  { name: 'Executive CEO', category: 'executive', description: 'CEO-level executive template', isPremium: true },
  { name: 'Executive CTO', category: 'executive', description: 'CTO executive design', isPremium: true },
  { name: 'Executive CFO', category: 'executive', description: 'CFO executive template', isPremium: true },
  { name: 'Executive COO', category: 'executive', description: 'COO executive design', isPremium: true },
  { name: 'Executive VP', category: 'executive', description: 'Vice President executive template', isPremium: true },
  { name: 'Executive Director', category: 'executive', description: 'Director-level executive design', isPremium: true },
  { name: 'Executive Leadership', category: 'executive', description: 'Leadership-focused executive template', isPremium: true },
  { name: 'Executive Strategy', category: 'executive', description: 'Strategic executive design', isPremium: true },
  { name: 'Executive Board', category: 'executive', description: 'Board member executive template', isPremium: true },
  { name: 'Executive Founder', category: 'executive', description: 'Founder executive design', isPremium: true },
  { name: 'Executive Partner', category: 'executive', description: 'Partner-level executive template', isPremium: true },
  { name: 'Executive Principal', category: 'executive', description: 'Principal executive design', isPremium: true },
  { name: 'Executive Senior', category: 'executive', description: 'Senior executive template', isPremium: true },
  { name: 'Executive Global', category: 'executive', description: 'Global executive design', isPremium: true },
  { name: 'Executive Tech', category: 'executive', description: 'Technology executive template', isPremium: true },
  { name: 'Executive Finance', category: 'executive', description: 'Finance executive design', isPremium: true },
  { name: 'Executive Healthcare', category: 'executive', description: 'Healthcare executive template', isPremium: true },
  { name: 'Executive Consulting', category: 'executive', description: 'Consulting executive design', isPremium: true },
  { name: 'Executive Manufacturing', category: 'executive', description: 'Manufacturing executive template', isPremium: true },
  { name: 'Executive Retail', category: 'executive', description: 'Retail executive design', isPremium: true },
  { name: 'Executive Media', category: 'executive', description: 'Media executive template', isPremium: true },
  { name: 'Executive Non-Profit', category: 'executive', description: 'Non-profit executive design', isPremium: true },
  { name: 'Executive Government', category: 'executive', description: 'Government executive template', isPremium: true },
  { name: 'Executive International', category: 'executive', description: 'International executive design', isPremium: true },
  { name: 'Executive Transformation', category: 'executive', description: 'Transformation executive template', isPremium: true },

  // Classic Category (25 templates)
  { name: 'Classic Traditional', category: 'classic', description: 'Traditional professional format', isPremium: false },
  { name: 'Classic Professional', category: 'classic', description: 'Classic professional design', isPremium: false },
  { name: 'Classic Corporate', category: 'classic', description: 'Corporate classic template', isPremium: false },
  { name: 'Classic Business', category: 'classic', description: 'Business classic design', isPremium: false },
  { name: 'Classic Conservative', category: 'classic', description: 'Conservative classic template', isPremium: false },
  { name: 'Classic Formal', category: 'classic', description: 'Formal classic design', isPremium: true },
  { name: 'Classic Academic', category: 'classic', description: 'Academic classic template', isPremium: false },
  { name: 'Classic Legal', category: 'classic', description: 'Legal profession classic design', isPremium: true },
  { name: 'Classic Finance', category: 'classic', description: 'Finance classic template', isPremium: false },
  { name: 'Classic Banking', category: 'classic', description: 'Banking classic design', isPremium: true },
  { name: 'Classic Government', category: 'classic', description: 'Government classic template', isPremium: false },
  { name: 'Classic Healthcare', category: 'classic', description: 'Healthcare classic design', isPremium: false },
  { name: 'Classic Insurance', category: 'classic', description: 'Insurance classic template', isPremium: true },
  { name: 'Classic Accounting', category: 'classic', description: 'Accounting classic design', isPremium: false },
  { name: 'Classic Engineering', category: 'classic', description: 'Engineering classic template', isPremium: false },
  { name: 'Classic Manufacturing', category: 'classic', description: 'Manufacturing classic design', isPremium: true },
  { name: 'Classic Education', category: 'classic', description: 'Education classic template', isPremium: false },
  { name: 'Classic Research', category: 'classic', description: 'Research classic design', isPremium: false },
  { name: 'Classic Non-Profit', category: 'classic', description: 'Non-profit classic template', isPremium: true },
  { name: 'Classic Senior', category: 'classic', description: 'Senior professional classic design', isPremium: true },
  { name: 'Classic Entry', category: 'classic', description: 'Entry-level classic template', isPremium: false },
  { name: 'Classic Mid-Level', category: 'classic', description: 'Mid-level classic design', isPremium: false },
  { name: 'Classic Experienced', category: 'classic', description: 'Experienced professional classic template', isPremium: true },
  { name: 'Classic Timeless', category: 'classic', description: 'Timeless classic design', isPremium: true },
  { name: 'Classic Elegant', category: 'classic', description: 'Elegant classic template', isPremium: true },

  // Technology Category (25 templates)
  { name: 'Tech Software Engineer', category: 'tech', description: 'Software engineer specialized template', isPremium: false },
  { name: 'Tech Full Stack', category: 'tech', description: 'Full stack developer template', isPremium: true },
  { name: 'Tech Frontend', category: 'tech', description: 'Frontend developer design', isPremium: false },
  { name: 'Tech Backend', category: 'tech', description: 'Backend developer template', isPremium: true },
  { name: 'Tech DevOps', category: 'tech', description: 'DevOps engineer design', isPremium: true },
  { name: 'Tech Data Science', category: 'tech', description: 'Data scientist template', isPremium: true },
  { name: 'Tech AI/ML', category: 'tech', description: 'AI/ML engineer design', isPremium: true },
  { name: 'Tech Product Manager', category: 'tech', description: 'Tech product manager template', isPremium: true },
  { name: 'Tech UX Designer', category: 'tech', description: 'UX designer tech template', isPremium: true },
  { name: 'Tech Security', category: 'tech', description: 'Cybersecurity specialist design', isPremium: true },
  { name: 'Tech Cloud', category: 'tech', description: 'Cloud engineer template', isPremium: true },
  { name: 'Tech Mobile', category: 'tech', description: 'Mobile developer design', isPremium: false },
  { name: 'Tech QA', category: 'tech', description: 'QA engineer template', isPremium: false },
  { name: 'Tech Architecture', category: 'tech', description: 'Solutions architect design', isPremium: true },
  { name: 'Tech Startup', category: 'tech', description: 'Tech startup template', isPremium: true },
  { name: 'Tech Enterprise', category: 'tech', description: 'Enterprise tech design', isPremium: true },
  { name: 'Tech Innovation', category: 'tech', description: 'Tech innovation template', isPremium: true },
  { name: 'Tech Research', category: 'tech', description: 'Tech research design', isPremium: false },
  { name: 'Tech Consulting', category: 'tech', description: 'Tech consulting template', isPremium: true },
  { name: 'Tech Leadership', category: 'tech', description: 'Tech leadership design', isPremium: true },
  { name: 'Tech Platform', category: 'tech', description: 'Platform engineer template', isPremium: true },
  { name: 'Tech Analytics', category: 'tech', description: 'Data analytics design', isPremium: false },
  { name: 'Tech Infrastructure', category: 'tech', description: 'Infrastructure template', isPremium: true },
  { name: 'Tech Blockchain', category: 'tech', description: 'Blockchain developer design', isPremium: true },
  { name: 'Tech Gaming', category: 'tech', description: 'Game developer template', isPremium: true },

  // Healthcare Category (25 templates)
  { name: 'Healthcare Nurse', category: 'healthcare', description: 'Registered nurse template', isPremium: false },
  { name: 'Healthcare Doctor', category: 'healthcare', description: 'Physician template', isPremium: true },
  { name: 'Healthcare Specialist', category: 'healthcare', description: 'Medical specialist design', isPremium: true },
  { name: 'Healthcare Administrator', category: 'healthcare', description: 'Healthcare administrator template', isPremium: false },
  { name: 'Healthcare Tech', category: 'healthcare', description: 'Healthcare technology design', isPremium: true },
  { name: 'Healthcare Research', category: 'healthcare', description: 'Medical research template', isPremium: true },
  { name: 'Healthcare Clinical', category: 'healthcare', description: 'Clinical professional design', isPremium: false },
  { name: 'Healthcare Mental Health', category: 'healthcare', description: 'Mental health professional template', isPremium: true },
  { name: 'Healthcare Therapy', category: 'healthcare', description: 'Therapist design', isPremium: false },
  { name: 'Healthcare Pharmacy', category: 'healthcare', description: 'Pharmacist template', isPremium: true },
  { name: 'Healthcare Emergency', category: 'healthcare', description: 'Emergency medicine design', isPremium: true },
  { name: 'Healthcare Surgery', category: 'healthcare', description: 'Surgical professional template', isPremium: true },
  { name: 'Healthcare Pediatric', category: 'healthcare', description: 'Pediatric specialist design', isPremium: true },
  { name: 'Healthcare Geriatric', category: 'healthcare', description: 'Geriatric care template', isPremium: false },
  { name: 'Healthcare Public Health', category: 'healthcare', description: 'Public health design', isPremium: false },
  { name: 'Healthcare Quality', category: 'healthcare', description: 'Quality assurance template', isPremium: true },
  { name: 'Healthcare Compliance', category: 'healthcare', description: 'Compliance specialist design', isPremium: true },
  { name: 'Healthcare Analytics', category: 'healthcare', description: 'Healthcare analytics template', isPremium: true },
  { name: 'Healthcare Management', category: 'healthcare', description: 'Healthcare management design', isPremium: true },
  { name: 'Healthcare Executive', category: 'healthcare', description: 'Healthcare executive template', isPremium: true },
  { name: 'Healthcare Innovation', category: 'healthcare', description: 'Healthcare innovation design', isPremium: true },
  { name: 'Healthcare Digital', category: 'healthcare', description: 'Digital health template', isPremium: true },
  { name: 'Healthcare Telehealth', category: 'healthcare', description: 'Telehealth design', isPremium: true },
  { name: 'Healthcare Policy', category: 'healthcare', description: 'Healthcare policy template', isPremium: false },
  { name: 'Healthcare Academic', category: 'healthcare', description: 'Academic medicine design', isPremium: true },

  // Finance Category (25 templates)
  { name: 'Finance Analyst', category: 'finance', description: 'Financial analyst template', isPremium: false },
  { name: 'Finance Investment', category: 'finance', description: 'Investment professional design', isPremium: true },
  { name: 'Finance Banking', category: 'finance', description: 'Banking professional template', isPremium: true },
  { name: 'Finance Accounting', category: 'finance', description: 'Accountant design', isPremium: false },
  { name: 'Finance Controller', category: 'finance', description: 'Financial controller template', isPremium: true },
  { name: 'Finance Executive', category: 'finance', description: 'Finance executive design', isPremium: true },
  { name: 'Finance Risk', category: 'finance', description: 'Risk management template', isPremium: true },
  { name: 'Finance Compliance', category: 'finance', description: 'Compliance specialist design', isPremium: false },
  { name: 'Finance Audit', category: 'finance', description: 'Auditor template', isPremium: false },
  { name: 'Finance Treasury', category: 'finance', description: 'Treasury professional design', isPremium: true },
  { name: 'Finance Portfolio', category: 'finance', description: 'Portfolio manager template', isPremium: true },
  { name: 'Finance Trading', category: 'finance', description: 'Trading professional design', isPremium: true },
  { name: 'Finance Corporate', category: 'finance', description: 'Corporate finance template', isPremium: true },
  { name: 'Finance Planning', category: 'finance', description: 'Financial planning design', isPremium: false },
  { name: 'Finance Advisory', category: 'finance', description: 'Financial advisor template', isPremium: true },
  { name: 'Finance Insurance', category: 'finance', description: 'Insurance professional design', isPremium: false },
  { name: 'Finance Real Estate', category: 'finance', description: 'Real estate finance template', isPremium: true },
  { name: 'Finance Consulting', category: 'finance', description: 'Financial consulting design', isPremium: true },
  { name: 'Finance Technology', category: 'finance', description: 'Fintech template', isPremium: true },
  { name: 'Finance Analytics', category: 'finance', description: 'Financial analytics design', isPremium: true },
  { name: 'Finance Strategy', category: 'finance', description: 'Financial strategy template', isPremium: true },
  { name: 'Finance Operations', category: 'finance', description: 'Finance operations design', isPremium: false },
  { name: 'Finance Startup', category: 'finance', description: 'Startup finance template', isPremium: true },
  { name: 'Finance Global', category: 'finance', description: 'Global finance design', isPremium: true },
  { name: 'Finance Digital', category: 'finance', description: 'Digital finance template', isPremium: true },

  // Academic Category (20 templates)
  { name: 'Academic Professor', category: 'academic', description: 'Professor academic CV', isPremium: false },
  { name: 'Academic Researcher', category: 'academic', description: 'Research scientist CV', isPremium: false },
  { name: 'Academic PhD', category: 'academic', description: 'PhD candidate CV', isPremium: false },
  { name: 'Academic Postdoc', category: 'academic', description: 'Postdoctoral researcher CV', isPremium: true },
  { name: 'Academic Faculty', category: 'academic', description: 'Faculty position CV', isPremium: true },
  { name: 'Academic Teaching', category: 'academic', description: 'Teaching-focused CV', isPremium: false },
  { name: 'Academic Research', category: 'academic', description: 'Research-focused CV', isPremium: true },
  { name: 'Academic Publications', category: 'academic', description: 'Publication-heavy CV', isPremium: true },
  { name: 'Academic Grant', category: 'academic', description: 'Grant-focused CV', isPremium: true },
  { name: 'Academic Conference', category: 'academic', description: 'Conference presentation CV', isPremium: false },
  { name: 'Academic International', category: 'academic', description: 'International academic CV', isPremium: true },
  { name: 'Academic STEM', category: 'academic', description: 'STEM academic CV', isPremium: false },
  { name: 'Academic Humanities', category: 'academic', description: 'Humanities academic CV', isPremium: false },
  { name: 'Academic Social Science', category: 'academic', description: 'Social science CV', isPremium: true },
  { name: 'Academic Medical', category: 'academic', description: 'Medical academic CV', isPremium: true },
  { name: 'Academic Engineering', category: 'academic', description: 'Engineering academic CV', isPremium: false },
  { name: 'Academic Business', category: 'academic', description: 'Business school CV', isPremium: true },
  { name: 'Academic Law', category: 'academic', description: 'Law school CV', isPremium: true },
  { name: 'Academic Policy', category: 'academic', description: 'Policy research CV', isPremium: true },
  { name: 'Academic Industry', category: 'academic', description: 'Academic to industry CV', isPremium: true }
];

export default templateData;